const actionTypes = {
  RES_LOADING: "RES_LOADING",
  RES_ERROR: "RES_ERROR",
  RES_SUCCESS: "RES_SUCCESS",

  PRODUCT_LOADING: "PRODUCT_LOADING",
  PRODUCT_ERROR: "PRODUCT_ERROR",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_ADD: "PRODUCT_ADD",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_CLEAR: "PRODUCT_CLEAR",
};

export default actionTypes;
